on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: node --version
      - uses: actions/checkout
      - run: npm install
      - run: node app.js